services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./config:/config
      - ./sites:/srv/sites
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: bridge
